# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AS_ControlPannelunit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 265)
        MainWindow.setStyleSheet("/* Main Background */\n"
"QMainWindow {\n"
"    background-color: #0b1220;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #0b1220;\n"
"    color: #d1d5db;\n"
"    font-family: Segoe UI;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Title */\n"
"QLabel#titleLabel {\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    color: #22d3ee;   /* soft cyan */\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Section Labels */\n"
"QLabel#sectionLabel {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #60a5fa;   /* light blue */\n"
"}\n"
"\n"
"/* Group Box */\n"
"QGroupBox {\n"
"    border: 1.5px solid #334155;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"    background-color: #020617;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px;\n"
"    color: #38bdf8;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #1f2937;\n"
"    border: 1.5px solid #475569;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    color: #e5e7eb;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #334155;\n"
"    border: 1.5px solid #38bdf8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"/* ACTIVE BUTTON (antenna selected) */\n"
"QPushButton:checked {\n"
"    background-color: #2563eb;   /* blue */\n"
"    color: white;\n"
"    border: 2px solid #60a5fa;\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    background-color: #020617;\n"
"    border: 1.5px solid #475569;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: #e5e7eb;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1.5px solid #38bdf8;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1.5px solid #2563eb;\n"
"}\n"
"\n"
"/* Dropdown */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #020617;\n"
"    border: 1px solid #475569;\n"
"    selection-background-color: #2563eb;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Line Edit */\n"
"QLineEdit {\n"
"    background-color: #020617;\n"
"    border: 1.5px solid #475569;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: #e5e7eb;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #2563eb;\n"
"}\n"
"\n"
"/* General Labels */\n"
"QLabel {\n"
"    color: #d1d5db;\n"
"font:18px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PB_ = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_.sizePolicy().hasHeightForWidth())
        self.PB_.setSizePolicy(sizePolicy)
        self.PB_.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PB_.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PB_.setObjectName("PB_")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PB_)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleLabel = QtWidgets.QLabel(self.PB_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_3.addWidget(self.titleLabel)
        self.frame_3 = QtWidgets.QFrame(self.PB_)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.CB_Portlist = QtWidgets.QComboBox(self.groupBox)
        self.CB_Portlist.setObjectName("CB_Portlist")
        self.horizontalLayout_2.addWidget(self.CB_Portlist)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LE_BaudRate = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_BaudRate.sizePolicy().hasHeightForWidth())
        self.LE_BaudRate.setSizePolicy(sizePolicy)
        self.LE_BaudRate.setObjectName("LE_BaudRate")
        self.horizontalLayout_2.addWidget(self.LE_BaudRate)
        self.PB_Connect = QtWidgets.QPushButton(self.groupBox)
        self.PB_Connect.setObjectName("PB_Connect")
        self.horizontalLayout_2.addWidget(self.PB_Connect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.PB_)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_HF1 = QtWidgets.QPushButton(self.frame_2)
        self.PB_HF1.setObjectName("PB_HF1")
        self.horizontalLayout.addWidget(self.PB_HF1)
        self.PB_HF2 = QtWidgets.QPushButton(self.frame_2)
        self.PB_HF2.setObjectName("PB_HF2")
        self.horizontalLayout.addWidget(self.PB_HF2)
        self.PB_HF_BACKUP_ANT = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.PB_HF_BACKUP_ANT.setFont(font)
        self.PB_HF_BACKUP_ANT.setObjectName("PB_HF_BACKUP_ANT")
        self.horizontalLayout.addWidget(self.PB_HF_BACKUP_ANT)
        self.PB_HF_Load = QtWidgets.QPushButton(self.frame_2)
        self.PB_HF_Load.setObjectName("PB_HF_Load")
        self.horizontalLayout.addWidget(self.PB_HF_Load)
        self.PB_HF_MAIN_ANT = QtWidgets.QPushButton(self.frame_2)
        self.PB_HF_MAIN_ANT.setObjectName("PB_HF_MAIN_ANT")
        self.horizontalLayout.addWidget(self.PB_HF_MAIN_ANT)
        self.PB_BW_HF_ANT = QtWidgets.QPushButton(self.frame_2)
        self.PB_BW_HF_ANT.setObjectName("PB_BW_HF_ANT")
        self.horizontalLayout.addWidget(self.PB_BW_HF_ANT)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "ANTEENA SWITVHING UNIT CONTROL PANEL"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Port"))
        self.label_2.setText(_translate("MainWindow", "Baud Rate"))
        self.PB_Connect.setText(_translate("MainWindow", "Connect"))
        self.PB_HF1.setText(_translate("MainWindow", "HF1"))
        self.PB_HF2.setText(_translate("MainWindow", "HF2"))
        self.PB_HF_BACKUP_ANT.setText(_translate("MainWindow", "HF BACKUP ANT"))
        self.PB_HF_Load.setText(_translate("MainWindow", "HF LOAD"))
        self.PB_HF_MAIN_ANT.setText(_translate("MainWindow", "HF MAIN ANT"))
        self.PB_BW_HF_ANT.setText(_translate("MainWindow", "BW HF ANT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
